version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels:
      - 'dependencies'
      - 'autosquash'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'feather-icons'
      - dependency-name: '@types/feather-icons'
