name: Feather

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * 1'

jobs:
  integration:
    runs-on: ubuntu-16.04
    name: CI
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install
        run: yarn install

      - name: check feather
        run: yarn feather

      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.AUTOSQUASH_TOKEN }}
          commit-message: Update feather-icons
          title: Update feather-icons
          body: Update feather-icons
          branch: update-feather-icons
          base: main
