name: Feather

on:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  integration:
    runs-on: ubuntu-16.04
    name: CI
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install
        run: yarn install

      - name: check feather
        run: yarn feather
